#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

while read line; do
    # Skip comments
    if [ "$(echo "$line" | cut -c1)" = "#" ]; then
        continue
    fi
    if [ "$(echo "$line" | wc -c)" -ge 72 ] || [ "$(echo "$line" | wc -c)" -le 10 ]; then
        echo -e "\033[0;31mThe length of the message has to be between 10 and 72 characters."
        exit 1
    fi
done < "$1"

exit 0
